### PR TITLE
Rename the python module from bbl to ardana-opsconsole-server

### PR DESCRIPTION
**Pull request by toabctl**
To be consistent in naming, rename it.
Also fix the license mentioned in setup.py, add the url and the author.

### CODE REVIEW

**Review by nicolasbock — APPROVED** [review]

**Review by jeremy-moffitt — APPROVED** [review]
At a glance this looks fine to me, should probably get input from @GarySmith

**Comment by jeremy-moffitt** [comment]
@toabctl since this repo syncs with gerrit, this change may need to be made there instead of directly in github

**Review by jeremy-moffitt — CHANGES_REQUESTED** [review]
see above about making this change in gerrit instead of directly in github... theres also some concern whether this will impact other parts of the code where its referred to as bll, not sure if this is just metadata or something more substantive

**Comment by toabctl** [comment]
Moving to gerrit

**Pull request closed without merging**
